export const ADDNEW_TODO = 'ADDNEW_TODO';
export const GETALL_TODO ='GETALL_TODO'; 
export const TOGGLE_TODO ='TOGGLE_TODO';
export  const UPDATE_TODO='UPDATE_TODO';
export const DELETE_TODO='DELETE_TODO';
export const TOGGLE_TAB ='TOGGLE_TAB'
export const ALL_TODOES='All Todos';
export const ACTIVE_TODOES = 'Active Todos';
export const DONE_TODOES = 'Done Todos'
export const TABS =[ALL_TODOES,ACTIVE_TODOES,DONE_TODOES]